### ISSUE TITLE
Adding DB files on the command line doesn't work

### ISSUE THREAD

**Issue by derek-keeler** [eniklas/gamatrix-gog#35]
Adding db files at the end of the command line causes errors in the current `argparse` mechanism.

Not sure if this is moot or not at this point, should we remove it?

**Comment by eniklas** [comment]
I believe it, I haven't passed in DB args since very early in development. I think it's nice to have, so if you want to run against a different set of users than what's in the config file, you can pass those in without editing the config file. But, since I've never used it in practice, we're not gonna miss it if we remove that functionality and just require the DBs to be in the config, and only allow subsets of those to be specified with `-u`.
